### PR TITLE
update web-dom version

### PR DESCRIPTION
**Pull request by athanclark**
Just a simple version change, although I do not know how this affects the package-sets.

### CODE REVIEW

**Comment by ethul** [comment]
Thanks!

**Comment by safareli** [comment]
This is actually a braking change

**Comment by safareli** [comment]
I think if version range was used, then it would have been less breaking.

**Comment by ethul** [comment]
I am not opposed to doing a major version bump, but I was following the
recommendation for semver:
https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Pull request merged**
